Спринт 12. Изменение функциональности по ТЗ
Irina-Gavrilina/java-filmorate pull request #4
Opened 2024-10-08 04:40 UTC by Irina-Gavrilina

2024-10-08 19:56 UTC, AlexanderSparrow requested changes
Отличная работа! Есть небольшие неточности и предложения по улучшению.

2024-10-08 19:56 UTC, AlexanderSparrow commented on README.md
> +![Схема базы данных проекта](./Scheme.png)
ОБЯЗАТЕЛЬНО
Принято размещать дополнительные ресурсы вне хранилища основного кода. Можно создать отдельную папку, например assets, и хранить их там. тогда путь будет указан как (/assets/если_есть_вложения/имя_файла.расширение)

2024-10-08 19:56 UTC, AlexanderSparrow commented on README.md
> +- `status` - статус запроса (confirmed/not confirmed)
ЖЕЛАТЕЛЬНО
Рассмотри возможность создания отдельной таблицы для хранения статусов дружбы — это гибкое и масштабируемое решение, которое лучше подходит для реляционной базы данных. Это позволит добавлять новые статусы или изменять существующие без изменения кода и пересборки приложения.

2024-10-08 19:56 UTC, AlexanderSparrow commented on README.md
> +SELECT * FROM users;
Рекомендация: В реальных приложениях лучше избегать SELECT * и явно указывать необходимые колонки, чтобы уменьшить объем возвращаемых данных и повысить читаемость кода.

2024-10-08 19:56 UTC, AlexanderSparrow commented on README.md
> +- Добавление нового пользователя:
Запрос корректен. Важно только убедиться, что все ограничения целостности (например, уникальность email) настроены в базе данных.

2024-10-08 19:56 UTC, AlexanderSparrow commented on README.md
> +- Получение списка друзей пользователя с id = 1:
ОБЯЗАТЕЛЬНО 
Этот запрос вернет только одного друга, потому что подзапрос ограничен до одного результата, в то время как нужно получить всех друзей. Для корректного получения списка друзей лучше использовать JOIN JOIN friendship AS f ON u.user_id = f.invitee_id.

2024-10-08 19:56 UTC, AlexanderSparrow commented on README.md
> +- Удаление пользователя с id = 1:
Запрос корректен но нужно проверить, что в базе данных настроены каскадные удаления, если пользователь связан с другими сущностями (например, с лайками или дружбой).

2024-10-08 19:56 UTC, AlexanderSparrow commented on README.md
> +- Получение 10 самых популярных фильмов:
ОБЯЗАТЕЛЬНО
Проверь логику подзапроса, поскольку подзапрос в условии WHERE возвращает несколько строк, что вызовет ошибку. Также здесь не происходит группировки по названиям фильмов.
Если нужен запрос 10 самых популярных фильмов, отсортированных по количеству лайков: 
SELECT f.name FROM films AS f
JOIN film_likes AS fl ON f.film_id = fl.film_id
GROUP BY f.film_id, f.name
ORDER BY COUNT(fl.user_id) DESC
LIMIT 10;

2024-10-09 11:34 UTC, Irina-Gavrilina commented on README.md
> +![Схема базы данных проекта](./Scheme.png)
Хорошо, буду знать на будущее, исправила

2024-10-09 11:35 UTC, Irina-Gavrilina commented on README.md
> +- `status` - статус запроса (confirmed/not confirmed)
Пока думаю оставить эту таблицу как есть, так как на данный момент не известно будет ли у нас поле status расчётным или нет. Если понадобится, то исправлю согласно будущим рекомендациям в ТЗ

2024-10-09 11:35 UTC, Irina-Gavrilina commented on README.md
> +- Получение списка друзей пользователя с id = 1:
Согласна, код запроса исправила

2024-10-09 11:35 UTC, Irina-Gavrilina commented on README.md
> +- Удаление пользователя с id = 1:
Хорошо, буду иметь в виду, что такое поведение лучше задавать при создании таблиц

2024-10-09 11:36 UTC, Irina-Gavrilina commented on README.md
> +- Получение 10 самых популярных фильмов:
Ок, код запроса исправила

2024-10-09 18:06 UTC, AlexanderSparrow approved these changes
Поздравляю! ОТличная работа!

2024-10-20 05:02 UTC, closed without merging